export enum ColumnId {
  SELECT = "SELECT",
  TITLE = "TITLE",
  AUTHOR = "AUTHOR",
  RESPONSE = "RESPONSE",
  LAST_MODIFICATION = "LAST_MODIFICATION",
  STATUS = "STATUS",
  SENDING_DATE = "SENDING_DATE",
}
