services:
   maven:
    image: "nexus-pic2.support-ent.fr/hub/maven-builder:latest"
    user: "$DEFAULT_DOCKER_USER"
    working_dir: /usr/src/maven
    volumes:
      - ./:/usr/src/maven
      - ~/.m2:/var/maven/.m2
    environment:
      MAVEN_CONFIG: /var/maven/.m2