services:
  node:
    image: opendigitaleducation/node:16-alpine-pnpm
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
      - ~/.npm:/.npm
      - ../../common:/home/node/app/common