services:
  node:
    image: opendigitaleducation/node:22-alpine-pnpm
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
      - ../../common:/home/node/app/common
      - ~/.npm:/.npm
