import { IForm, IInfoImg } from "~/core/models/form/types";

export const makeMockedForm = (id: number): IForm => ({
  id,
  title: `Form #${String(id)}`,
  description: null,
  picture: null,
  owner_id: `owner-${String(id)}`,
  owner_name: `Owner ${String(id)}`,
  date_creation: new Date(2025, 0, id),
  date_modification: new Date(2025, 1, id),
  date_opening: null,
  date_ending: null,
  sent: id === 1,
  collab: id === 2,
  reminded: id === 3,
  archived: false,
  multiple: id === 4,
  anonymous: id === 5,
  is_public: id === 6,
  public_key: `public-key-${String(id)}`,
  response_notified: id === 7,
  editable: true,
  is_progress_bar_displayed: id === 8,
  rgpd: true,
  rgpd_goal: null,
  rgpd_lifetime: 365,
  folder_id: id * 10,
  nb_elements: id * 4,
  nb_responses: null,
  infoImg: {
    name: `Image ${String(id)}`,
    type: id === 8 ? "image/png" : "image/jpeg",
    compatible: id === 9,
  } as IInfoImg,
  rights: [],
});
