services:
  node:
    image: "nexus-pic2.support-ent.fr/hub/node-builder:latest"
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
      - ../../common:/home/node/app/common
      - ~/.npm:/.npm
