export enum OverElementType {
  QUESTION_ROOT = "QUESTION_ROOT",
  QUESTION_SECTION = "QUESTION_SECTION",
  SECTION = "SECTION",
  SECTION_TOP = "SECTION_TOP",
  SECTION_BOTTOM = "SECTION_BOTTOM",
}

export enum ActiveElementType {
  QUESTION_ROOT = "QUESTION_ROOT",
  QUESTION_SECTION = "QUESTION_SECTION",
  SECTION = "SECTION",
}

// S = SECTION
// ST = SECTION_TOP
// SB = SECTION_BOTTOM
// QR = QUESTION_ROOT
// QS = QUESTION_SECTION
export enum DndMove {
  // S->S
  // S->QR 
  // QR->QR
  SWITCH_ROOT_ELEMENTS = "SWITCH_ROOT_ELEMENTS",
  // QS->QS
  // QS->ST
  // QS->SB
  SWITCH_QUESTIONS_SECTION = "SWITCH_QUESTIONS_SECTION",
  // QR->QS
  // QR->ST 
  // QR->SB 
  // QS->QR
  // QR->ST
  // QR->SB
  SWITCH_QUESTION_SECTION_WITH_QUESTION_ROOT = "SWITCH_QUESTION_SECTION_WITH_QUESTION_ROOT",
}